(function(){'use strict';var e;var k=function(a){if("function"==typeof a.gwdLoad&&"function"==typeof a.gwdIsLoaded&&!a.gwdIsLoaded()){var c=h(a),b=c&&"function"==typeof c.gwdIsLoaded;(!c||b&&c.gwdIsLoaded())&&a.gwdLoad()}},l=function(a){if(null==a.gwdActivate||"function"==typeof a.gwdActivate)if(null==a.gwdIsActive||!a.gwdIsActive()){var c=h(a),b=c&&null!=c.gwdIsActive&&"function"==typeof c.gwdIsActive;null==c&&a.gwdActivate();b&&c.gwdIsActive()&&a.gwdActivate()}},m=function(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==
a.getAttribute("is")},h=function(a){if(m(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&m(a))return a;return null},n=function(a){for(var c=[];a;a=a.parentNode)c.unshift(a);return c},p=function(a,c,b){var d=d||c;a.hasAttribute(c)?(a=a.getAttribute(c),b.setAttribute(d,a)):b.removeAttribute(d)};var q=function(a,c){setTimeout(a,c)};var r=function(a,c,b){if(b){var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,b)}else d=document.createEvent("Event"),d.initEvent(a,!0,!0);c.dispatchEvent(d)},t=function(a,c){var b=function(d){a.removeEventListener("playing",b);c(d)};a.addEventListener("playing",b)};var u={G:"fullscreenchange",O:"MSFullscreenChange",I:"webkitfullscreenchange",H:"mozfullscreenchange"},v={G:"fullscreenElement",I:"webkitFullscreenElement",H:"mozFullScreenElement"},w=function(a){var c;for(c in v){var b=a[v[c]];if(void 0!==b)break}return b||null},x=function(a){var c=document;this.j="has-fullscreen-gwd-video";this.b=c;this.f=a;this.w=this.L.bind(this)};
x.prototype.L=function(){var a=w(this.b);if(a)if(this.f==a){var c=this.b;for(a=this.f;a&&a!=c;a=a.parentNode)a.classList.add(this.j)}else if(a.classList.contains(this.j)){c=n(this.f);a=n(a);for(var b=0,d=c[0],f=a[0],g=null;d&&f&&d==f;)g=d,b++,d=c[b],f=a[b];y(this,g)}else y(this);else y(this)};x.prototype.install=function(){for(var a in u)this.b.addEventListener(u[a],this.w)};var y=function(a,c){c=c||a.b;for(var b=a.f;b&&b!=c;b=b.parentNode)b.classList.remove(a.j)};var z="abort canplay canplaythrough durationchange emptied ended error loadeddata loadedmetadata loadstart pause play playing progress ratechange seeked seeking stalled suspend timeupdate volumechange waiting".split(" "),A="autoplay loop muted sources controls poster".split(" "),B={".avi":1,".m4v":1,".mp4":1,".mpeg":1,".mpg":1,".ogg":1,".ogv":1,".qt":1,".webm":1,".wmv":1},C=function(){};goog.inherits(C,HTMLElement);e=C.prototype;
e.createdCallback=function(){for(var a=0;a<this.children.length;a++){var c=this.children[a];if(c.classList.contains("intermediate-element")){this.removeChild(c);break}}this.a=document.createElement("video");this.F=this.J.bind(this);this.v=function(b){r(b.type,this,b.detail)}.bind(this);this.A=new x(this.a);this.l=this.m=!1;for(a=0;a<A.length;a++)p(this,A[a],this.a);this.a.setAttribute("webkit-playsinline","");this.a.setAttribute("playsinline","");this.a.setAttribute("x-webkit-airplay","allow");this.u=
1;this.o=!1;a=document.createElement("div");a.classList.add("intermediate-element");a.appendChild(this.a);this.appendChild(a);Object.defineProperty(this,"nativeElement",{enumerable:!0,get:function(){return this.a}});Object.defineProperty(this,"autoplay",{enumerable:!0,get:function(){return this.a.autoplay},set:function(b){b?this.setAttribute("autoplay",""):this.removeAttribute("autoplay")}});Object.defineProperty(this,"loop",{enumerable:!0,get:function(){return this.a.loop},set:function(b){b?this.setAttribute("loop",
""):this.removeAttribute("loop")}});Object.defineProperty(this,"muted",{enumerable:!0,get:function(){return this.a.muted},set:function(b){b?(this.setAttribute("muted",""),this.a.muted=!0):(this.removeAttribute("muted"),this.a.muted=!1)}});this.muted=this.hasAttribute("muted");Object.defineProperty(this,"controls",{enumerable:!0,get:function(){return this.a.controls},set:function(b){b?this.setAttribute("controls",""):this.removeAttribute("controls")}});Object.defineProperty(this,"poster",{enumerable:!0,
get:function(){return this.a.poster},set:function(b){b?this.setAttribute("poster",b):this.removeAttribute("poster")}});Object.defineProperty(this,"paused",{enumerable:!0,get:function(){return this.a.paused}});Object.defineProperty(this,"volume",{enumerable:!0,get:function(){return this.a.volume},set:function(b){this.a.volume=b}});Object.defineProperty(this,"currentTime",{enumerable:!0,get:function(){return this.a.currentTime},set:function(b){this.a.currentTime=b}});Object.defineProperty(this,"duration",
{enumerable:!0,get:function(){return this.a.duration}});Object.defineProperty(this,"width",{enumerable:!0,get:function(){return this.a.width},set:function(b){b&&(this.a.width=b)}});Object.defineProperty(this,"height",{enumerable:!0,get:function(){return this.a.height},set:function(b){b&&(this.a.height=b)}});Object.defineProperty(this,"videoWidth",{enumerable:!0,get:function(){return this.a.videoWidth}});Object.defineProperty(this,"videoHeight",{enumerable:!0,get:function(){return this.a.videoHeight}});
this.g=this.muted&&-1!=(window.navigator.userAgent||"").indexOf("Android");this.i=this.c=null;this.interactiveVideoComponents=[];this.K=function(){for(var b=0;b<this.interactiveVideoComponents.length;b++)this.interactiveVideoComponents[b].handleVideoTimeUpdate()}.bind(this);this.D=function(){this.c||(this.c=setInterval(this.K,33))}.bind(this);this.h=function(){this.c&&(clearInterval(this.c),this.c=null)}.bind(this);this.B=this.C=null;this.s=function(){if(this.parentElement){var b=this.getBoundingClientRect();
if(b.width!=this.C||b.height!=this.B)for(this.C=b.width,this.B=b.height,b=0;b<this.interactiveVideoComponents.length;b++)this.interactiveVideoComponents[b].resizeHandlerNeeded&&this.interactiveVideoComponents[b].resize()}}.bind(this);this.M=function(){this.i||(this.i=setInterval(this.s,250))}.bind(this);this.N=function(){this.i&&clearInterval(this.i)}.bind(this)};
e.attachedCallback=function(){k(this);l(this);this.g&&t(this.a,function(){this.g&&(this.a.volume=0)}.bind(this));this.a.addEventListener("volumechange",this.F,!1);for(var a=0;a<z.length;a++)this.a.addEventListener(z[a],this.v,!1);this.A.install();this.a.addEventListener("play",this.D,!1);this.a.addEventListener("pause",this.h,!1);this.a.addEventListener("ended",this.h,!1)};
e.detachedCallback=function(){var a=this.A,c;for(c in u)a.b.removeEventListener(u[c],a.w);a.f==w(a.b)&&y(a);this.g&&(this.a.volume=1);this.a.removeEventListener("volumechange",this.F,!1);for(a=0;a<z.length;a++)this.a.removeEventListener(z[a],this.v,!1);this.h();this.a.removeEventListener("play",this.D,!1);this.a.removeEventListener("pause",this.h,!1);this.a.removeEventListener("ended",this.h,!1)};
e.setResizeObserver=function(){for(var a=!1,c=0;c<this.interactiveVideoComponents.length;c++)if(this.interactiveVideoComponents[c].resizeHandlerNeeded){a=!0;break}a?(this.M(),window.addEventListener("resize",this.s,!1)):(this.N(),window.removeEventListener("resize",this.s,!1))};
e.attributeChangedCallback=function(a){if("sources"==a){if(this.m){var c=this.a.paused,b=this.muted;D(this);this.a.load();q(function(){this.muted=b;c?this.pause():this.play()}.bind(this),0)}}else"muted"==a&&(this.a.muted=this.muted);"class"!=a&&"id"!=a&&p(this,a,this.a)};e.gwdActivate=function(){this.autoplay&&this.a.paused&&q(function(){this.play()}.bind(this),200);this.l=!0};e.gwdDeactivate=function(){this.hasAttribute("resumable")||this.seek(0);this.pause();this.l=!1};e.gwdIsActive=function(){return this.l};
e.gwdLoad=function(){D(this);this.m=!0;r("ready",this)};e.gwdIsLoaded=function(){return this.m};e.mute=function(){this.g&&(this.a.volume=1);this.g=!1;this.muted=!this.muted};e.replay=function(){this.seek(0);this.play()};e.seek=function(a){this.currentTime!=a&&(this.currentTime=a)};e.J=function(){!1===this.o&&!0===this.muted&&0===this.u&&(this.a.volume=1,this.muted=!1);this.u=this.a.volume;this.o=this.muted};
e.setVolume=function(a){this.muted=0<a?!1:!0;this.a.volume=a/100;this.u=this.a.volume;this.o=this.muted};e.setSources=function(a){this.setAttribute("sources",a)};e.play=function(){this.a.play()};e.pause=function(){this.a.pause()};
var D=function(a){var c=a.getAttribute("sources");c=E(c);for(var b=a.a.children.length-1;0<=b;b--){var d=a.a.children[b];"source"==d.tagName.toLowerCase()&&a.a.removeChild(d)}for(b=0;b<c.length;++b){d=document.createElement("source");var f=c[b];f=f.trim();f=window.Enabler?Enabler.getUrl(f):f;d.src=f;a.a.appendChild(d)}},E=function(a){var c=[];if(!a)return c;a=a.split(",").map(function(F){return F.trim()});for(var b="",d=0;d<a.length;d++){var f=a[d];b+=f;var g=f.lastIndexOf(".");-1!=g?B[f.substring(g).toLowerCase()]?
(c.push(b),b=""):b+=",":b+=","}b&&c.push(b.substring(0,b.length-1));return c};document.registerElement("gwd-video",{prototype:C.prototype});}).call(this);
